In [2]:
import numpy as np

In [ ]:
np.__version__

In [ ]:
np.array([1, 3.14, "hello"])

In [ ]:
age = [15, 18, 22]
npage = np.array(age, dtype=np.float32)
npage

In [ ]:
np.ones(shape=(2, 3), dtype=np.int64)

In [ ]:
np.ones(shape=(3), dtype=np.int8)

In [ ]:
np.ones(shape=(1, 3), dtype=np.int8)

In [ ]:
np.zeros(shape=(2, 3), dtype=np.int64)

In [ ]:
np.full(shape=(2, 3), fill_value=6, dtype=np.int64)

In [ ]:
np.eye(N=3, M=4, k=0, dtype=np.int8)

In [ ]:
np.random.randint(0, 100, size=(3, 3))

In [ ]:
np.random.randn(100)

In [25]:
np.random.normal(loc=170, scale=5, size=(3, 3))

array([[167.95092125, 172.0962921 , 170.9002746 ],
       [166.57951576, 164.67353153, 171.90560958],
       [170.83618188, 182.39999295, 168.91287962]])

In [26]:
# 生成0-1之间的随机数
np.random.random(size=(3, 3))

array([[0.00701017, 0.4152869 , 0.77940512],
       [0.66294042, 0.60692413, 0.78655365],
       [0.10019024, 0.33838115, 0.53930667]])

In [35]:
# 生成随机索引
np.random.permutation(100)

array([ 4, 18,  8, 51, 72, 17, 16,  1, 10, 33,  6, 87, 65, 89, 74, 15, 42,
       96, 47, 20, 78, 52, 53, 64, 28, 19, 68, 30, 93, 63, 97, 38, 39, 32,
       86, 44, 77,  9, 34, 37, 23, 56, 70, 50,  7, 29, 36, 75, 27, 60, 21,
       99, 73, 12, 90, 91, 54, 81, 76, 98, 57, 25, 31, 35, 49, 71, 48,  3,
       58, 61, 11, 55, 41, 92, 22, 62, 67, 82, 45, 46, 79, 13, 84, 88, 66,
        0, 40, 26, 95, 43, 85, 59, 24, 94,  5,  2, 80, 69, 83, 14])

In [38]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr2[0][1]

np.int64(2)

In [42]:
arr2[0, 1]

np.int64(2)

In [43]:
arr2[1, 2]

np.int64(6)